name: Build and deploy Python app to Azure Web App - pdg-chatbot-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create deployment package
        run: |
          rm -rf deploy_package  # Xóa thư mục cũ nếu tồn tại
          mkdir deploy_package  # Tạo thư mục mới
          rsync -av --exclude=deploy_package --exclude=venv --exclude=.git ./ deploy_package/  # Sao chép mã nguồn trừ thư mục không cần thiết
          zip -r deploy_package.zip deploy_package/  # Nén lại thành deploy_package.zip

      - name: Upload source code for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy_package.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Ensure startup script is executable
        run: chmod +x startup.sh

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A2C4E8FE1F5E48829FFEE12603944B83 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_83C26C2CE7DC47F1A48F75189C0E19E7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B1F26A5593EE4B7799A76A9C59858008 }}

      - name: Deploy source code to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'pdg-chatbot-web'
          slot-name: 'Production'
          package: deploy_package.zip  # Chỉ upload file ZIP

      - name: Restart Azure Web App
        run: |
          az webapp restart --name pdg-chatbot-web --resource-group pdg-ai-resource